require conf/distro/poky.conf
DISTRO = "custom-a53"
DISTRO_NAME = "Custom A53 Distro"
DISTRO_VERSION = "1.0"
LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"


RPI_USE_U_BOOT = "1"
ENABLE_UART = "1"
UBOOT_DELAY = "5"

DISTRO_FEATURES:append = " systemd usrmerge u-boot"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""

#RDEPENDS:packagegroup-core-boot:remove = "sysvinit sysvinit-inittab"
#PACKAGE_EXCLUDE = "sysvinit sysvinit-inittab sysvinit-pidof"
