BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "customa53"
BBFILE_PATTERN_customa53 := "^${LAYERDIR}/"
BBFILE_PRIORITY_customa53 = "12"

LAYERSERIES_COMPAT_customa53 = "scarthgap"
